[package]
name = "fute-rs"
version = "0.1.3"
authors = ["Jake O'Shannessy <joshannessy@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
chid = {path = "../../red-smoke/chid"}
clap = {version = "3", features = ["cargo"]}
csv = "1"
fds-input-parser = {path = "../../red-smoke/fds-input-parser"}
env_logger = "0.9"
lazy_static = "1"
log = "0.4"
fute-core = { path = "../fute-core-rs" }
plotters = "0.3"
prettytable-rs = "0.8"
num-format = "0.4"
data-vector = { git = "https://github.com/JakeOShannessy/data-vector.git"}
# data-vector = { path = "../../data-vector"}
url = "2"
chrono = "0.4"
serde_json = "1"
walkdir = "2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["shellapi"] }
