[package]
name = "fute-rs"
version = "0.1.1"
authors = ["Jake O'Shannessy <joshannessy@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
csv = "1.1.1"
env_logger = "0.6.2"
log = "0.4.0"
fute-core = { path = "../fute-core-rs" }
plotters = { git = "https://github.com/38/plotters.git" }
prettytable-rs = "0.8.0"
num-format = "0.4.0"
data-vector = { git = "https://github.com/JakeOShannessy/data-vector.git"}
winapi = { version = "0.3.8", features = ["shellapi"] }
url = "2.1.1"
