resolver: lts-12.5
packages:
  - ./fds-utilities
  - ./fds-case-manage
  - ./fds-quick-monitor-program
  - ./fute-core
extra-deps:
  - attoparsec-binary-0.2
  - Chart-1.9.1
  - Chart-diagrams-1.9.2
  - time-1.6.0.1
  - gnuplot-0.5.6
  - git: https://github.com/JakeOShannessy/namelist-parser.git
    commit: 8c0148c088c10c4580dd127153555d077977d05a
  - git: https://github.com/JakeOShannessy/fds-input-parser.git
    commit: f5963f2d736c9f50fc2f662834be500db70901f0
  - git: https://github.com/Soostone/formattable.git
    commit: fd5494a56c28c4656d35e34b50c86df8d4685211
  - directory-1.3.3.2@sha256:79e15a62f90cb9f20f46b2b56fe67d00d71ed54cfad07ea337695f9ebb74baa4,2829
  - process-1.6.5.1@sha256:77a9afeb676357f67fe5cf1ad79aca0745fb6f7fb96b786d510af08f622643f6,2468
  - unix-2.7.2.2


# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

allow-newer: true
