[package]
name = "fute-core"
version = "0.1.0"
authors = ["Jake O'Shannessy <joshannessy@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1.1"
data-vector = { git = "https://github.com/JakeOShannessy/data-vector.git"}
fds-input-parser = {version = "^0.1.3", git = "https://github.com/JakeOShannessy/fds-input-parser-rs.git"}
nom = "5.0.1"
version-compare = "0.0.10"
