[package]
name = "fute-core"
version = "0.1.0"
authors = ["Jake O'Shannessy <joshannessy@gmail.com>"]
edition = "2018"

[dependencies]
fds-input-parser = {git = "ssh://git@github.com/JakeOShannessy/fds-input-parser-rs.git"}
nom = "5.0.1"
version-compare = "0.0.10"
