[package]
name = "fute-core"
version = "0.1.3"
authors = ["Jake O'Shannessy <joshannessy@gmail.com>"]
edition = "2018"

[dependencies]
arrayvec = "0.5"
chrono = {version = "0.4", features = ["serde"] }
csv = "1"
data-vector = { git = "https://github.com/JakeOShannessy/data-vector.git"}
# data-vector = { path = "../../data-vector"}
downcast-rs = "1"
# fds-input-parser = {path = "../../fds-input-parser-rs"}
fds-input-parser = {version = "0.1.3", git = "https://github.com/JakeOShannessy/fds-input-parser-rs.git"}
nom = "5"
regex = "1"
serde = { version = "1", features = ["derive"] }
version-compare = "0.0.11"
